# Demonstrates files.file attrset API, treefmt integration,
# global formatters, per-file format overrides, and onChange hooks.
{
  perSystem =
    { pkgs, ... }:
    {
      files.generateApp = true;

      # --- treefmt integration ---
      # all files.file entries are auto-formatted through treefmt
      treefmt.programs.nixfmt.enable = true;
      files.treefmt.enable = true;

      # --- global formatter by extension ---
      # applied to all .json files unless overridden per-file
      files.formatters.json =
        name: drv:
        pkgs.runCommand "jqfmt-${name}" { nativeBuildInputs = [ pkgs.jq ]; } ''
          jq --sort-keys . < ${drv} > $out
        '';

      # --- files.file attrset API ---

      # text content — auto-formatted by nixfmt via treefmt
      files.file."config.nix".text = "{foo=1;bar=2;}";

      # source from structured data — formatted by global .json formatter
      files.file."data/config.json".source = pkgs.writers.writeJSON "config.json" {
        version = 1;
        features = {
          treefmt = true;
          formatters = true;
        };
      };

      # executable script
      files.file."scripts/greet.sh" = {
        text = ''
          #!/bin/sh
          echo "hello from files!"
        '';
        executable = true;
      };

      # onChange hook with runtimeInputs
      files.file.".envrc" = {
        text = "use flake";
        onChange = {
          runtimeInputs = [ pkgs.direnv ];
          script = "direnv allow || true";
        };
      };

      # per-file format override — takes priority over treefmt and global formatters
      files.file."NOTICE".text = "generated by files";
      files.file."NOTICE".format =
        name: drv:
        pkgs.runCommand "upper-${name}" { } ''
          tr '[:lower:]' '[:upper:]' < ${drv} > $out
        '';

      # disable a file (useful for overriding shared module defaults)
      files.file."disabled-example.txt".text = "this won't be written";
      files.file."disabled-example.txt".enable = false;

      # --- files.files list API ---
      # both APIs can be used together; list entries get the same formatting
      # pipeline (treefmt, global formatters, per-file format)
      files.files = [
        {
          path = "data/version.txt";
          drv = pkgs.writeText "version.txt" "0.1.0";
        }
        {
          path = "data/manifest.json";
          drv = pkgs.writers.writeJSON "manifest.json" {
            name = "demo";
            version = "0.1.0";
          };
          # per-file format works in the list API too
          format =
            name: drv:
            pkgs.runCommand "jqfmt-${name}" { nativeBuildInputs = [ pkgs.jq ]; } ''
              jq --sort-keys . < ${drv} > $out
            '';
        }
      ];
    };
}
